services:
  database:
    image: postgres:13
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST=db
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - "5432"
    restart: always

  web:
    build: ./app/.
    ports:
      - 5000:5000
    volumes:
      - postgres-data:/app
    depends_on:
      - database

volumes:
  postgres-data:
